version: '3.7'

services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: mongo-server
    container_name: my-mongo-server
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: dbGrids
    ports:
      - "27017:27017"
    networks:
      - linkednetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-server
    container_name: my-client-server
    command: npm run dev
    env_file:
      - .env.local
    volumes:
      - ./client:/usr/app/client:cached
      - /usr/app/client/node_modules
    ports:
      - "10000:10000"
    depends_on:
      - mongo
    networks:
      - linkednetwork

volumes:
  data-volume:

networks:
  linkednetwork:
